In [4]:
import h5py

/home/raj/anaconda2/envs/htkProject/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
f=h5py.File('TCGAopt','r')
dset=f.keys()

In [13]:
dset[0]

u'features'

In [14]:
dset[1]

u'x_centroid'

In [15]:
dset[2]

u'y_centroid'

In [21]:
import numpy as np

In [22]:
n1=f.get('features')
n1

<HDF5 dataset "features": shape (2891, 32, 32, 3), type "<f4">

In [23]:
n1=np.array(n1)
n1.shape

(2891, 32, 32, 3)

In [30]:
print(type(n1))

<type 'numpy.ndarray'>


In [31]:
print(n1[2])

[[[250. 213. 242.]
  [250. 213. 241.]
  [249. 212. 241.]
  ...
  [248. 212. 240.]
  [248. 212. 243.]
  [248. 212. 243.]]

 [[250. 213. 243.]
  [249. 213. 243.]
  [249. 213. 243.]
  ...
  [249. 212. 241.]
  [249. 212. 243.]
  [248. 212. 243.]]

 [[250. 213. 243.]
  [249. 214. 243.]
  [249. 214. 242.]
  ...
  [249. 212. 242.]
  [249. 212. 244.]
  [249. 212. 244.]]

 ...

 [[249. 214. 242.]
  [249. 213. 242.]
  [249. 213. 242.]
  ...
  [249. 213. 241.]
  [249. 213. 241.]
  [249. 213. 242.]]

 [[249. 212. 244.]
  [250. 212. 244.]
  [250. 214. 244.]
  ...
  [249. 213. 241.]
  [249. 213. 241.]
  [249. 213. 242.]]

 [[248. 213. 242.]
  [250. 213. 241.]
  [249. 212. 241.]
  ...
  [249. 213. 242.]
  [249. 213. 242.]
  [248. 213. 242.]]]


In [32]:
print(n1[2])

[[[248. 212. 242.]
  [248. 212. 243.]
  [248. 212. 243.]
  ...
  [249. 213. 241.]
  [249. 213. 239.]
  [249. 213. 242.]]

 [[247. 212. 243.]
  [248. 212. 243.]
  [248. 212. 243.]
  ...
  [249. 213. 242.]
  [249. 213. 239.]
  [249. 213. 241.]]

 [[248. 212. 243.]
  [248. 212. 244.]
  [248. 212. 243.]
  ...
  [249. 213. 242.]
  [249. 213. 241.]
  [249. 213. 241.]]

 ...

 [[248. 212. 243.]
  [248. 212. 242.]
  [248. 213. 243.]
  ...
  [249. 213. 243.]
  [249. 213. 243.]
  [250. 213. 242.]]

 [[248. 212. 243.]
  [248. 212. 243.]
  [248. 211. 242.]
  ...
  [247. 212. 243.]
  [247. 212. 243.]
  [249. 213. 243.]]

 [[249. 213. 242.]
  [249. 213. 242.]
  [249. 213. 241.]
  ...
  [249. 213. 240.]
  [248. 213. 241.]
  [248. 213. 240.]]]


In [33]:
print(n1[3])

[[[249. 213. 241.]
  [249. 213. 243.]
  [249. 213. 243.]
  ...
  [249. 213. 241.]
  [249. 213. 241.]
  [249. 213. 242.]]

 [[249. 213. 243.]
  [249. 213. 243.]
  [249. 213. 242.]
  ...
  [249. 213. 242.]
  [249. 213. 241.]
  [249. 213. 240.]]

 [[249. 213. 244.]
  [249. 213. 242.]
  [248. 213. 240.]
  ...
  [249. 213. 243.]
  [249. 213. 241.]
  [249. 213. 240.]]

 ...

 [[249. 213. 239.]
  [248. 213. 239.]
  [249. 213. 241.]
  ...
  [249. 213. 241.]
  [248. 213. 243.]
  [248. 213. 244.]]

 [[249. 213. 243.]
  [249. 213. 243.]
  [249. 213. 243.]
  ...
  [248. 212. 241.]
  [247. 212. 243.]
  [248. 212. 244.]]

 [[248. 212. 242.]
  [248. 212. 242.]
  [248. 212. 242.]
  ...
  [249. 213. 241.]
  [248. 213. 241.]
  [248. 213. 241.]]]


In [34]:
print(n1[0])

[[[249. 213. 242.]
  [249. 213. 242.]
  [249. 213. 242.]
  ...
  [249. 214. 240.]
  [249. 214. 242.]
  [249. 213. 243.]]

 [[249. 213. 242.]
  [249. 213. 242.]
  [249. 213. 242.]
  ...
  [248. 212. 240.]
  [248. 212. 241.]
  [249. 212. 243.]]

 [[249. 213. 242.]
  [249. 213. 242.]
  [249. 213. 242.]
  ...
  [248. 212. 240.]
  [248. 212. 240.]
  [249. 212. 243.]]

 ...

 [[249. 213. 241.]
  [249. 213. 243.]
  [249. 213. 243.]
  ...
  [249. 213. 242.]
  [249. 213. 242.]
  [247. 212. 242.]]

 [[250. 213. 242.]
  [249. 213. 242.]
  [249. 213. 241.]
  ...
  [249. 213. 242.]
  [249. 213. 243.]
  [247. 214. 244.]]

 [[247. 212. 242.]
  [247. 213. 242.]
  [247. 213. 242.]
  ...
  [249. 213. 243.]
  [249. 214. 243.]
  [249. 214. 243.]]]


In [35]:
n2=f.get('x_centroid')
n2

<HDF5 dataset "x_centroid": shape (2891, 1), type "<f8">

In [36]:
n2=np.array(n2)
n2.shape

(2891, 1)

In [37]:
print(n2[0])

[17.]


In [38]:
print(n2[:15])

[[17. ]
 [17. ]
 [17. ]
 [17. ]
 [17. ]
 [17. ]
 [17. ]
 [51.5]
 [51.5]
 [51.5]
 [51.5]
 [51.5]
 [51.5]
 [51.5]
 [85.5]]


In [39]:
print(n2[16:30])

[[ 85.5]
 [ 85.5]
 [ 85.5]
 [ 85.5]
 [ 85.5]
 [119.5]
 [119.5]
 [119.5]
 [119.5]
 [119.5]
 [119.5]
 [119.5]
 [153.5]
 [153.5]]
